title: trnzt
description: a site for digging into data on transit systems around the world
author: trnzt
timezone: America/Los_Angeles
baseurl: ""
url: https://trnzt.com
google:
  api_key: AIzaSyCHHFNX99565xWe1vLOpxean3ZVoCWn-Gs
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
plugins:
  - jekyll-sitemap
exclude:
  - charts/
  - CNAME
  - Dockerfile
  - gulpfile.js
  - nginx.conf
  - package-lock.json
  - package.json
  - scss/
